meta_product_name: "SunnYogi"
meta_title: "SunnYogi - The new reference for online yoga"
meta_description: "SunnYogi is the new online plateform to pick your own yoga sesion "
meta_image: "logo.jpg"
twitter_account: ""
